included:
  - BankManagerUIApp

excluded:
  - Pods

opt_in_rules:
  - empty_count
  - empty_string
  - operator_usage_whitespace
  - force_unwrapping
  - closure_spacing
  - implicitly_unwrapped_optional
  - private_outlet
  - private_action
  - weak_delegate
  - vertical_whitespace_closing_braces

disabled_rules:
  - trailing_whitespace
  - orphaned_doc_comment
  - line_length
  - unused_optional_binding
